settings_version: 0.0.4
datasets_dir: E:\Samsung Innovation Campus\Project\datasets
weights_dir: e:\Samsung Innovation Campus\Project\Streamlit\weights
runs_dir: e:\Samsung Innovation Campus\Project\Streamlit\runs
uuid: 90ba3b016240e975a37e165623f6f41eb9dd5ce5bc5d721063a28315a54f06d2
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
